### PR TITLE
Code cleanup and fixes

### PR DESCRIPTION
**Pull request by zachlowry**

### CODE REVIEW

**Comment by zachlowry** [comment]
Can we merge this in? Could really use the fixed Group support for the project I'm working on.

**Comment by brianjmiller** [comment]
Can you list the fixes that were made? Doing both formatting and fixes in a single PR makes it hard to review. Were unit tests added to make sure the fixes are maintained (and actually fixed)? Sorry for the delay I knew the other one was still outstanding but forgot about this one.

**Comment by zachlowry** [comment]
Sure:

PEP8 formatting
Group entity now contains fields from Agent
Property fields are now initialized in the constructor
Fixed date conversion routine in iso8601.py (there was a default case in the if statement that would have raised an exception)

**Comment by zachlowry** [comment]
Oh, and there aren't any new tests due to these changes, but several tests were modified.

**Comment by brianjmiller** [comment]
@zachlowry please have a look at and merge the commit here https://github.com/brianjmiller/TinCanPython/commit/b50946e1c4af6afe52d29145115c16621e126f75 to this PR. The changes were necessary to get to a fully quiet `pep8` run for my installation. If you want to, you could also merge or rebase to the current master to get the Travis commits with unit test fixes here and we can add running of `pep8` to the travis config. If you don't want to bother with that we'll get this rolled into master and then make those changes. I'm hoping to finally get this cleared out.

**Comment by brianjmiller** [comment]
Ultimately we probably need to look at getting pyflakes run, possibly switching to flake8 to kill two birds with one package.

**Comment by zachlowry** [comment]
Got this merged into my branch, back to you @brianjmiller. Thanks!

**Comment by brianjmiller** [comment]
@zachlowry something very strange happened with the history, there should not have been conflicts and I don't know why your original commit shows up twice. Can we clean that up?

**Comment by zachlowry** [comment]
My git-fu isn't strong enough to do this, I don't think.

**Comment by brianjmiller** [comment]
All right in good shape now. Over to you @bscSCORM.

**Pull request merged**
